### ISSUE TITLE
Compilation error with wasm_bindgen

### ISSUE THREAD

**Issue by barvirm** [uuid-rs/uuid#653]
Hello dear developers.

**What happened?**
I'm trying to use Uuid structure for wasm-bindgen, but I get compiler errors.
![image](https://user-images.githubusercontent.com/15948420/213251217-b4034f0f-4f02-4aa9-98ec-7ebf14376e2c.png)

``` rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Foo(pub uuid::Uuid);
```

**What were you expecting?**
No compiler error from building it with: `wasm-pack build --target nodejs`

**What's the context?**
- Target: wasm32-unknow-unknow, rust version rustc 1.66.0-beta.2 (0040709e3 2022-11-20)
```toml
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
uuid = { version = "1.2.2", features = ["v4", "js", "serde", "wasm-bindgen"] }
```
